.\" $Id: shformatconverter.1,v 1 2008/03/27 16:00 kseunari Exp $

.TH shformatconverter 1

.SH NAME
shformatconverter \- Converts spherical harmonics from third party programs into the
format used by camino.

.SH SYNOPSIS
.B shformatconveter [-source <tournier>]

.SH DESCRIPTION
This program reorders spherical harmonic coeffients output from third party programs so
that they can be read by Camino.  The format Camino expects is:

[c00, c20, Re(c21), Im(c21), Re(c22), Im(c22), c40, Re(c41), Im(c41), ...]

Currently, the program can read the output from Tourniers Spherical Deconvolution (SD)
code.

.SH EXAMPLES

To convert the file sdCoeffs.Bfloat from Tournier's SD code, which has been saved as
big-endian floats, use the command:

shformatconverter -source tournier -inputdatatype float -outputdatatype double <
sdCoeffs.Bfloat > sdCoeffs_Camino.Bdouble

 
.SH OPTIONS
.TP
.B \-source \fR <\fI tournier \fR>
The source flag is used to define the origin of the input spherical harmonic
coefficients.  Currently only Tourniers SD code is supported.

.TP
.B \-inputdatatype \fR <\fI double | float \fR>
The format of the input data.  It is assumed to be big-endian format.

.TP
.B \-outputdatatype \fR <\fI double | float \fR>
The format of the output data.	It is assumed to be big-endian format.

.SH AUTHORS
Kiran K Seunarine <camino@cs.ucl.ac.uk>

.SH "SEE ALSO"

.SH BUGS
