.\" $Id: function_name.1,v version_number yyyy/mm/dd time authorname Exp $

.TH function_name 1

.SH NAME
function_name \- One sentence to describe the usage of the function.

.SH SYNOPSIS
.B function_name -compulsory options <parameters> [-optional options <parameters | other>]

.SH DESCRIPTION
Use one or two paragraphs to describe the function in details.

.SH EXAMPLES

Give function using examples and explanations, which cover the most typical usage
situations.

.SH OPTIONS
.TP
.B \-option1 \fR <\fI parameters \fR>
Explain option1 in detail...  It might be worth mentioning relevant camino functions
after explanation of every option.

.TP
.B \-option2 \fR <\fI parameters \fR>
Explain option2 in detail... 

.SH AUTHORS
Author Name(s) <camino@cs.ucl.ac.uk>

.SH "SEE ALSO"
List relevant camino functions, in the format of function_name(1) e.g. modelfit(1),
datasynth(1).

.SH BUGS
